import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "YouTube Summary Generator",
  description:
    "Paste a YouTube URL and get a concise, detailed, or key-takeaways summary generated by AI. Includes timestamps, copy-to-clipboard, PDF export, and a beautiful responsive UI.",
  keywords: [
    "YouTube",
    "summary",
    "AI",
    "transcript",
    "video summary",
    "OpenAI",
  ],
  authors: [{ name: "YouTube Summary Generator" }],
  openGraph: {
    title: "YouTube Summary Generator",
    description:
      "AI-powered YouTube video summaries with timestamps and PDF export.",
    type: "website",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafc" },
    { media: "(prefers-color-scheme: dark)", color: "#090b12" },
  ],
};

const themeInitScript = `
(function() {
  try {
    var stored = localStorage.getItem('ysg-theme');
    var systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    var theme = stored || (systemPrefersDark ? 'dark' : 'light');
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
        />
      </head>
      <body className="min-h-screen antialiased">
        {children}
        <Toaster
          position="top-center"
          richColors
          closeButton
          toastOptions={{
            classNames: {
              toast:
                "rounded-xl border border-[rgb(var(--border))] bg-[rgb(var(--card))] text-[rgb(var(--card-foreground))] shadow-lg",
            },
          }}
        />
      </body>
    </html>
  );
}
